---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shopflow-gitops-repo
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: shopflow-gitops-repo
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .token }}"
        url: "{{ .url }}"
        type: "{{ .type }}"
  dataFrom:
  - extract:
      key: shopflow/github-pat
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitops-auth
  namespace: tekton-builds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: gitops-auth
    template:
      type: Opaque
      data:
        token: "{{ .token }}"
  dataFrom:
  - extract:
      key: shopflow/github-pat
