apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: docker-build-push
  namespace: tekton-builds
spec:
  params:
    - name: image
      type: string
      description: Full image URL including tag
    - name: context
      type: string
      description: Path to Dockerfile context relative to source root
    - name: dockerfile
      type: string
      default: Dockerfile
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.22.0
      env:
        - name: AWS_REGION
          value: "eu-west-1"
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/
      command:
        - /kaniko/executor
      args:
        - "--dockerfile=$(params.context)/$(params.dockerfile)"
        - "--context=$(workspaces.source.path)/source"
        - "--destination=$(params.image)"
        - "--cache=true"
        - "--cache-ttl=24h"
  volumes:
    - name: docker-config
      configMap:
        name: docker-config
