apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
  - ../../base/apps
  - ../../base/datastores
  - namespace.yaml

images:
  - name: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/shopflow/frontend
    newName: 122610497964.dkr.ecr.eu-west-1.amazonaws.com/shopflow/frontend
    newTag: main
  - name: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/shopflow/cart-service
    newName: 122610497964.dkr.ecr.eu-west-1.amazonaws.com/shopflow/cart-service
    newTag: main
  - name: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/shopflow/order-service
    newName: 122610497964.dkr.ecr.eu-west-1.amazonaws.com/shopflow/order-service
    newTag: main
  - name: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/shopflow/payment-service
    newName: 122610497964.dkr.ecr.eu-west-1.amazonaws.com/shopflow/payment-service
    newTag: main
  - name: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/shopflow/product-service
    newName: 122610497964.dkr.ecr.eu-west-1.amazonaws.com/shopflow/product-service
    newTag: main
  - name: ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/shopflow/user-service
    newName: 122610497964.dkr.ecr.eu-west-1.amazonaws.com/shopflow/user-service
    newTag: main

patches:
  - target:
      kind: Service
      name: frontend
      namespace: ecommerce
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer
