# App-of-Apps pattern: one ArgoCD Application manages all app cluster apps
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saranca14/shopflow-gitops.git
    targetRevision: main
    path: clusters/app
    directory:
      recurse: true
  destination:
    name: app  # Registered cluster name in ArgoCD
    namespace: ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
