---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saranca14/shopflow-gitops.git
    targetRevision: main
    path: clusters/observability
  destination:
    server: https://A259AB33B3C06A04FB9DFD24C57F36E1.gr7.eu-west-1.eks.amazonaws.com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
