apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopflow-portal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/saranca14/shopflow-portal.git
    targetRevision: main
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
